/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Administrator' at '18-1-19 上午9:17' with Gradle 2.14.1
 *
 * @author Administrator, @date 18-1-19 上午9:17
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
